name: CrackedLogin
version: 0.0.1
load: STARTUP
author: krconv
main: krconverse.bukkit.crackedlogin.CrackedLogin
depend: [ProtocolLib]
commands:
    whois:
        description: Retrieves information about the owner of the given user.
        usage: /whois <player>
        permission: crackedlogin.command.whois
        permission-message: §cYou don't have permission.
permissions:
    crackedlogin.command.whois:
        description: Gives access to /whois command
        default: false