name: CrackedLogin
version: 0.0.1
load: STARTUP
author: krconv
main: krconverse.bukkit.crackedlogin.CrackedLogin
depend: [ProtocolLib]
commands:
    whois:
        description: Retrieves information about the owner of the given user.
        usage: /whois <player>
        permission-message: You don't have permission.