authentication:
  URL:
    UseHTTPS: true
    Host: hostname
    Path: path
    Port: port
    Timeout: timeout
  Timeout: 7
  AllowedPackets:
  - KEEP_ALIVE
  - LOGIN
  - KICK_DISCONNECT
messages:
  AuthenticationNotOnlineKick: We couldn't reach the authentication server! You should contact an administrator.
  NotRegisteredLoginKick: You are not registered!
  BannedLoginKick: You are banned!
  OtherLoginKick: You cannot log in! Contact an administrator if you believe this is incorrect.
  TimeoutKick: You must enter your password to login!
  InvalidLogin: Invalid login attempt!
  BannedKick: You have been banned!
