name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
load: STARTUP
author: krconv
main: ${project.properties.mainClassPath}
softdepend: [PacketListenerApi]